### ISSUE TITLE
Remove `wasmedge_sys_ffi` and use upstream `wasmedge-sys::ffi`

### ISSUE THREAD

**Issue by jprendes** [second-state/wasmedge_plugin_rust_sdk#7]
The package `wasmedge_sys_ffi` is doing exactly the same as the upstream `wasmedge-sys::ffi`, but `wasmedge-sys` has more features, like the `standalone` feature.
There doesn't seem to be any particular value added by `wasmedge_sys_ffi`.

**Comment by hydai** [comment]
@apepkuss  @L-jasmine 
Could you please check this? It is okay to use the `wasmedge-sys::ffi` instead of the existing `wasmedge_sys_ffi`.
